apiVersion: apps/v1
kind: Deployment
metadata:
  name: p9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p9
  template:
    metadata:
      labels:
        app: p9
    spec:
      containers:
      - image: dorowu/ubuntu-desktop-lxde-vnc:focal-lxqt
        name: p9
        ports:
        - containerPort: 80
